#spring.application.name=attest

spring.datasource.url=jdbc:postgresql://localhost:5432/attest
spring.datasource.username=postgres
spring.datasource.password=devpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
