package com.attest.attest;

import com.attest.attest.service.JwtService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.bouncycastle.crypto.digests.Blake2bDigest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.RequestPostProcessor;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.Signature;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.not;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.multipart;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Exercises the actual HTTP challenge -> sign -> verify flow, using a real
 * Ed25519 keypair generated in-test. The "sign like a wallet would" helpers
 * below deliberately reimplement Sui's intent-wrapping/BLAKE2b/address-derivation
 * scheme independently from SuiSignatureVerifier's production code, rather than
 * calling into it — reusing the same code for both sides of a signature test
 * would let a shared bug cancel itself out. The scheme's correctness itself is
 * separately, externally validated in SuiSignatureVerifierTests against a
 * signature generated by @mysten/sui's own SDK; this test's job is the HTTP
 * plumbing and the nonce lifecycle (single-use, tamper and replay rejection).
 */
@SpringBootTest
@AutoConfigureMockMvc
class AuthSecurityIntegrationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JwtService jwtService;

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void challengeThenVerifyIssuesATokenAndTheNonceCannotBeReplayed() throws Exception {
        String ip = "198.51.100.30";
        KeyPair keyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        String address = suiAddressFor(keyPair.getPublic());

        JsonNode challenge = objectMapper.readTree(
                mockMvc.perform(post("/api/auth/wallet/challenge").with(remoteIp(ip)))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString());

        String nonce = challenge.get("nonce").asText();
        String message = challenge.get("message").asText();
        assertContains(message, nonce);

        String signature = signLikeAWallet(keyPair, message);
        String verifyBody = objectMapper.writeValueAsString(
                new WalletVerifyPayload(nonce, address, signature));

        mockMvc.perform(post("/api/auth/wallet/verify").with(remoteIp(ip + "1"))
                        .contentType(MediaType.APPLICATION_JSON).content(verifyBody))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.suiAddress", is(address)))
                .andExpect(jsonPath("$.role", is("SIGNER")))
                .andExpect(jsonPath("$.token", not(is(""))));

        // Replaying the exact same (nonce, signature) must be rejected — the
        // nonce was already consumed by the request above.
        mockMvc.perform(post("/api/auth/wallet/verify").with(remoteIp(ip + "2"))
                        .contentType(MediaType.APPLICATION_JSON).content(verifyBody))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void verifyRejectsASignatureThatDoesNotMatchTheClaimedAddress() throws Exception {
        String ip = "198.51.100.40";
        KeyPair signerKeyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        KeyPair someoneElsesKeyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        String someoneElsesAddress = suiAddressFor(someoneElsesKeyPair.getPublic());

        JsonNode challenge = objectMapper.readTree(
                mockMvc.perform(post("/api/auth/wallet/challenge").with(remoteIp(ip)))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString());

        String nonce = challenge.get("nonce").asText();
        String message = challenge.get("message").asText();

        // Signed by signerKeyPair, but the request claims someone else's address.
        String signature = signLikeAWallet(signerKeyPair, message);
        String verifyBody = objectMapper.writeValueAsString(
                new WalletVerifyPayload(nonce, someoneElsesAddress, signature));

        mockMvc.perform(post("/api/auth/wallet/verify").with(remoteIp(ip + "1"))
                        .contentType(MediaType.APPLICATION_JSON).content(verifyBody))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void verifyRejectsAnUnknownNonce() throws Exception {
        KeyPair keyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        String address = suiAddressFor(keyPair.getPublic());
        String signature = signLikeAWallet(keyPair, "some message never issued by /challenge");

        String verifyBody = objectMapper.writeValueAsString(
                new WalletVerifyPayload("nonce-that-was-never-issued", address, signature));

        mockMvc.perform(post("/api/auth/wallet/verify").with(remoteIp("198.51.100.50"))
                        .contentType(MediaType.APPLICATION_JSON).content(verifyBody))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void protectedEndpointRejectsMissingAndMalformedJwt() throws Exception {
        mockMvc.perform(post("/api/documents/1/verify").with(remoteIp("198.51.100.20")))
                .andExpect(status().isUnauthorized());

        mockMvc.perform(post("/api/documents/1/verify").with(remoteIp("198.51.100.21"))
                        .header("Authorization", "Bearer definitely-not-a-jwt"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void aFreshWalletAccountBelongsToNoTeamAndCannotUpload() throws Exception {
        String ip = "198.51.100.60";
        KeyPair keyPair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair();
        String address = suiAddressFor(keyPair.getPublic());

        JsonNode challenge = objectMapper.readTree(
                mockMvc.perform(post("/api/auth/wallet/challenge").with(remoteIp(ip)))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString());
        String nonce = challenge.get("nonce").asText();
        String message = challenge.get("message").asText();
        String signature = signLikeAWallet(keyPair, message);

        JsonNode verifyResult = objectMapper.readTree(
                mockMvc.perform(post("/api/auth/wallet/verify").with(remoteIp(ip + "1"))
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(new WalletVerifyPayload(nonce, address, signature))))
                        .andExpect(status().isOk())
                        .andReturn().getResponse().getContentAsString());
        String token = verifyResult.get("token").asText();

        // This brand-new account belongs to no team, so uploading to any team
        // must be forbidden — access is governed by team membership, not the
        // account's global role.
        mockMvc.perform(multipart("/api/documents/team/1").with(remoteIp(ip + "2"))
                        .header("Authorization", "Bearer " + token)
                        .file(new MockMultipartFile("file", "document.pdf", "application/pdf", "%PDF-1.4\ncontent".getBytes())))
                .andExpect(status().isForbidden());
    }

    private void assertContains(String haystack, String needle) {
        if (!haystack.contains(needle)) {
            throw new AssertionError("Expected \"" + haystack + "\" to contain \"" + needle + "\"");
        }
    }

    // --- "sign like a wallet would", independent of production code ---------

    private static final byte[] ED25519_X509_PREFIX =
            HexFormat.of().parseHex("302a300506032b6570032100");

    private String signLikeAWallet(KeyPair keyPair, String message) throws Exception {
        byte[] messageBytes = message.getBytes(StandardCharsets.UTF_8);
        byte[] digest = personalMessageDigest(messageBytes);

        Signature signer = Signature.getInstance("Ed25519");
        signer.initSign(keyPair.getPrivate());
        signer.update(digest);
        byte[] rawSignature = signer.sign();

        byte[] rawPublicKey = rawEd25519PublicKeyBytes(keyPair.getPublic());

        byte[] serialized = new byte[1 + rawSignature.length + rawPublicKey.length];
        serialized[0] = 0; // Ed25519 scheme flag
        System.arraycopy(rawSignature, 0, serialized, 1, rawSignature.length);
        System.arraycopy(rawPublicKey, 0, serialized, 1 + rawSignature.length, rawPublicKey.length);
        return Base64.getEncoder().encodeToString(serialized);
    }

    private String suiAddressFor(PublicKey publicKey) {
        byte[] rawPublicKey = rawEd25519PublicKeyBytes(publicKey);
        byte[] flagged = new byte[1 + rawPublicKey.length];
        flagged[0] = 0;
        System.arraycopy(rawPublicKey, 0, flagged, 1, rawPublicKey.length);

        Blake2bDigest blake2b256 = new Blake2bDigest(256);
        blake2b256.update(flagged, 0, flagged.length);
        byte[] digest = new byte[blake2b256.getDigestSize()];
        blake2b256.doFinal(digest, 0);
        return "0x" + HexFormat.of().formatHex(digest);
    }

    private byte[] rawEd25519PublicKeyBytes(PublicKey publicKey) {
        byte[] x509 = publicKey.getEncoded();
        return Arrays.copyOfRange(x509, ED25519_X509_PREFIX.length, x509.length);
    }

    private byte[] personalMessageDigest(byte[] message) {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        buffer.write(3); // IntentScope.PersonalMessage
        buffer.write(0); // IntentVersion.V0
        buffer.write(0); // AppId.Sui
        writeUleb128(buffer, message.length);
        buffer.writeBytes(message);

        Blake2bDigest blake2b256 = new Blake2bDigest(256);
        byte[] input = buffer.toByteArray();
        blake2b256.update(input, 0, input.length);
        byte[] digest = new byte[blake2b256.getDigestSize()];
        blake2b256.doFinal(digest, 0);
        return digest;
    }

    private static void writeUleb128(ByteArrayOutputStream out, int value) {
        while (true) {
            int sevenBits = value & 0x7F;
            value >>>= 7;
            if (value == 0) {
                out.write(sevenBits);
                return;
            }
            out.write(sevenBits | 0x80);
        }
    }

    private RequestPostProcessor remoteIp(String ip) {
        return request -> {
            request.setRemoteAddr(ip);
            return request;
        };
    }

    private record WalletVerifyPayload(String nonce, String address, String signature) {}
}
