package com.attest.attest;

import com.attest.attest.exception.UnsupportedSignatureSchemeException;
import com.attest.attest.service.SuiSignatureVerifier;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The Ed25519 fixtures below are NOT hand-constructed — they were generated by
 * actually running {@code @mysten/sui}'s own Ed25519Keypair.signPersonalMessage
 * (the installed frontend dependency, the same code a real wallet uses) against
 * the exact message text WalletAuthService.buildMessage produces. This is a
 * direct cross-check of this class's intent-wrapping, BLAKE2b-256, Ed25519, and
 * address-derivation logic against Sui's own reference implementation — not an
 * assumption about the wire format.
 */
class SuiSignatureVerifierTests {

    private static final String MESSAGE_TEXT =
            "Sign in to Attest\n\n" +
            "This request will not trigger a blockchain transaction or cost any gas.\n\n" +
            "Nonce: abc123XYZ_-nonceValue\n" +
            "Issued at: 2026-09-13T12:00:00Z\n" +
            "Expires at: 2026-09-13T12:05:00Z";

    private static final String ADDRESS = "0x8f811104c0a2508f8d35f2de5cd2ab815527dcb7564cf9676dc8284839d9ee73";

    private static final String SIGNATURE_B64 =
            "AM4YUdoyCMcpeWktZZAMwNwLQsHsZCqHC0eo8L8dPyrGYYWZ+N/1NQ8ugFKAQz23B5aRT/DPKc9DSWiKC6bhngvLJkmVZTwSOAjPE7S1vXPYoac9s066vqSDJg+oAw7/7g==";

    // Unused by every test here — none of them exercise the zkLogin scheme,
    // which is the only path that ever calls this URL.
    private final SuiSignatureVerifier verifier = new SuiSignatureVerifier("http://localhost:3000/api/verify-zklogin");

    @Test
    void acceptsAGenuineEd25519SignatureFromMystenSSownSdk() {
        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), SIGNATURE_B64, ADDRESS);
        assertTrue(valid, "a real @mysten/sui-produced signature over the exact message must verify");
    }

    @Test
    void rejectsTheSameSignatureAgainstAnyOtherMessage() {
        String tamperedMessage = MESSAGE_TEXT + " ";
        boolean valid = verifier.verifyPersonalMessage(
                tamperedMessage.getBytes(StandardCharsets.UTF_8), SIGNATURE_B64, ADDRESS);
        assertFalse(valid);
    }

    @Test
    void rejectsTheSameSignatureAgainstADifferentClaimedAddress() {
        String someoneElsesAddress = "0x" + "1".repeat(64);
        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), SIGNATURE_B64, someoneElsesAddress);
        assertFalse(valid);
    }

    @Test
    void rejectsATamperedSignatureByte() {
        byte[] sigBytes = Base64.getDecoder().decode(SIGNATURE_B64);
        sigBytes[10] ^= 0x01; // flip a bit inside the signature portion
        String tampered = Base64.getEncoder().encodeToString(sigBytes);

        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), tampered, ADDRESS);
        assertFalse(valid);
    }

    @Test
    void rejectsGarbageThatIsNotValidBase64() {
        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), "not-base64!!!", ADDRESS);
        assertFalse(valid);
    }

    @Test
    void rejectsAnEmptySignature() {
        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), "", ADDRESS);
        assertFalse(valid);
    }

    @Test
    void rejectsAWrongLengthEd25519SignaturePayload() {
        // Valid flag byte (0 = Ed25519), but too short to contain a real signature + key.
        String tooShort = Base64.getEncoder().encodeToString(new byte[]{0, 1, 2, 3});
        boolean valid = verifier.verifyPersonalMessage(
                MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), tooShort, ADDRESS);
        assertFalse(valid);
    }

    @Test
    void throwsForAnUnrecognizedSchemeFlag() {
        // Flag 4 is not assigned to any scheme in Sui's signature-scheme table.
        byte[] bogus = new byte[1 + 64 + 32];
        bogus[0] = 4;
        String serialized = Base64.getEncoder().encodeToString(bogus);

        assertThrows(UnsupportedSignatureSchemeException.class, () ->
                verifier.verifyPersonalMessage(MESSAGE_TEXT.getBytes(StandardCharsets.UTF_8), serialized, ADDRESS));
    }
}
